FROM python:3.11-slim-bookworm

WORKDIR /gateway

COPY app/gateway/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/gateway/ .

ENV MT5_API_PORT=5001

EXPOSE 5001

CMD ["python", "app.py"]
